### ISSUE TITLE
Does this still work ?

### ISSUE THREAD

**Issue by MSZ-Spyro** [vardecab/otomoto_olx-scraper#1]
Hello, does it still work ? I keep getting 

```
python3 otomoto2.py
Starting...
First run - no file exists.
File doesn't exist.
Folder created: 220626-152532
Page URL: https://is.gd/Eews0U
How many pages are there to crawl? 1
Page number: 1 / 1
Waiting for 2 seconds before opening URL...
<●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●> 2/2 [100%] in 2.2s (0.91/s) 
Opening page...
Scraping page...
[########################################] (!) 0 in 0.1s (0.00/s) 
Successfully added 0 cars to file.
Reading file to clean up...
Cleaning the file...
There are 0 cars in total.
File cleaned up. New lines added.
Keyword wasn't provided - not searching.
Variable not defined. Keyword wasn't provided.
Traceback (most recent call last):
  File "otomoto2.py", line 253, in <module>
    counter2
NameError: name 'counter2' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "otomoto2.py", line 258, in <module>
    file_previous_run = open('output/' + previous_run_datetime + '/2-clean.txt', 'r') # 1st file 
NameError: name 'previous_run_datetime' is not defined
```

**Comment by vardecab** [comment]
Hey @MSZ-Spyro 👋🏼 Thanks for flagging.
